language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

notifications:
  email: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2


before_install:
  - mysql -e "create database IF NOT EXISTS testbench;" -uroot
  - mysql -e "CREATE USER 'sco'@'localhost' IDENTIFIED BY 'sco';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON testbench.* TO 'sco'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
